services:
  app:
    tty: true
    restart: always
    image: booking-app
    container_name: booking-app
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - application
    volumes:
      - .:/src/app
    command: air -c .air.toml

networks:
  application:
